name: Dev deployment from Github to AWS
on:
  push:
    branches:
      - master

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Dockerfile.dev
        run: docker build -t dawnmd/docker-react -f Dockerfile.dev .
      
      - name: Run Dockerfile Test
        run: docker run -e CI=true dawnmd/docker-react npm run test -- --coverage
        
      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"
        
      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time
        
      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"
          
#       - name: Install Dependencies & Deploy to AWS
#         run: |
#           sudo npm install -g beanstalk-deploy --unsafe-perm
#           sudo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}} beanstalk-deploy "docker-react" "DockerReact-env-1" "docker-react-${{ steps.format-time.outputs.replaced }}" "us-east-2" deploy.zip

      - name: Beanstalk Deploy
  # You may pin to the exact commit or the version.
  # uses: einaregilsson/beanstalk-deploy@af31173a6a0ffcbde0bd555ee228e34cd9bb63f8
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-south-1
          application_name: docker-react
          environment_name: Dockerreact-env
          version_label: docker-react-${{ steps.format-time.outputs.replaced }}
          deployment_package: deploy.zip
