name: Dev deployment from Github to AWS
on:
  push:
    branches:
      - master

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Dockerfile.dev
        run: docker build -t dawnmd/docker-react -f Dockerfile.dev .
      
      - name: Run dockerfile test
        run: docker run -e CI=true dawnmd/docker-react npm run test
